name: Draft release

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release draft
        id: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: 'OUTDATED'
          message: |
            Draft Release ready at ${{ steps.release.outputs.url }}
